preprocess:
  input: data/data.csv
  output: data/data_preprocessed.csv
  X_sm: data/processed/X_sm.csv
  y_sm: data/processed/y_sm.csv
   
train:
  y_train: data/for_training/y_train.csv
  X_train: data/for_training/X_train.csv

model: models/model.pkl


evaluation:
  y_test: data/test_eval/y_test.csv
  X_test: data/test_eval/X_test.csv

mlflow:
  uri: "http://host.docker.internal:5000"


#/Applications/Docker.app/Contents/Resources/bin/docker run -p 80:80 classification-app
#/Applications/Docker.app/Contents/Resources/bin/docker build -t classification-app .